### ISSUE TITLE
ux suggestion: Show description/tooltip on buttons on hover 

### ISSUE THREAD

**Issue by tmc** [GenAICollective/demo-night-app#2]
It'd be helpful to show an indication of what the main buttons in the demo phase do. 

<img width="485" alt="Screenshot 2024-05-30 at 7 10 46 PM" src="https://github.com/GenAICollective/demo-night-app/assets/3977/1c9d4083-2e8b-4891-8b1a-a9e9a28a5b4f">

**Comment by chappyasel** [comment]
<img width="424" alt="Screenshot 2024-06-16 at 12 54 46 PM" src="https://github.com/GenAICollective/demo-night-app/assets/13221124/ec9115b5-f8ea-4f31-8b62-d4561385cba5">

👨‍🍳

**Comment by tmc** [comment]
🔥
